import { Clause } from '../types';
import { DocumentSummary } from './documentSummary';

export const exportToText = (clauses: Clause[], summary: DocumentSummary, documentName: string): string => {
  const exportDate = new Date().toLocaleDateString();
  
  return `
LEGALEASE DOCUMENT ANALYSIS REPORT
Generated on: ${exportDate}
Document: ${documentName}

=====================================
EXECUTIVE SUMMARY
=====================================

${summary.overview}

=====================================
KEY TERMS AT A GLANCE
=====================================

• Rent Amount: ${summary.keyTerms.rentAmount}
• Lease Duration: ${summary.keyTerms.leaseDuration}
• Security Deposit: ${summary.keyTerms.securityDeposit}
• Late Fee Penalty: ${summary.keyTerms.lateFeePenalty}

=====================================
MAJOR RISKS IDENTIFIED
=====================================

${summary.majorRisks.map((risk, index) => `${index + 1}. ${risk}`).join('\n')}

=====================================
YOUR OBLIGATIONS
=====================================

${summary.yourObligations.map((obligation, index) => `${index + 1}. ${obligation}`).join('\n')}

=====================================
LANDLORD OBLIGATIONS
=====================================

${summary.landlordObligations.map((obligation, index) => `${index + 1}. ${obligation}`).join('\n')}

=====================================
FINANCIAL IMPACT
=====================================

• Monthly Commitment: ${summary.financialImpact.monthlyCommitment}
• Potential Penalties: ${summary.financialImpact.potentialPenalties}
• Total Cost Estimate: ${summary.financialImpact.totalCostEstimate}

=====================================
DETAILED CLAUSE ANALYSIS
=====================================

${clauses.map((clause, index) => `
CLAUSE ${index + 1}: ${clause.section}
Risk Level: ${clause.riskLevel.toUpperCase()} ${clause.category.toUpperCase()}

Original Text:
${clause.original}

Simplified Version:
${clause.simplified}

---
`).join('')}

=====================================
DISCLAIMER
=====================================

This analysis was generated by LegalEase AI and is for informational purposes only. 
It does not constitute legal advice. Please consult with a qualified attorney for 
legal guidance specific to your situation.

Report generated by LegalEase - AI Legal Document Simplification
  `.trim();
};

export const downloadTextFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};